#!/usr/bin/env python3
from __future__ import annotations

import argparse
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from pipeline_utils import read_json, utc_now_iso, write_json


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build legacy and bilingual v2 announcements for the timetable app.")
    parser.add_argument("--out", required=True, help="Output directory for announcements.json and announcements-v2.json.")
    parser.add_argument(
        "--announcements",
        default="config/announcements.json",
        help="Optional manual announcements JSON config (default: config/announcements.json).",
    )
    parser.add_argument(
        "--status",
        default="dist/.scrape-status.json",
        help="Scrape status file generated by scripts/scrape.py (default: dist/.scrape-status.json).",
    )
    return parser.parse_args()


def _load_manual_items(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    payload = read_json(path)
    if isinstance(payload, dict) and isinstance(payload.get("items"), list):
        return [item for item in payload["items"] if isinstance(item, dict)]
    raise ValueError(f"{path}: expected an object with an 'items' array.")


def _load_status(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    payload = read_json(path)
    if isinstance(payload, dict):
        return payload
    raise ValueError(f"{path}: expected a JSON object.")


def _auto_failure_announcement(status: dict[str, Any]) -> dict[str, Any] | None:
    failures = status.get("failures")
    if not isinstance(failures, list) or not failures:
        return None

    generated_at = status.get("generatedAt")
    if isinstance(generated_at, str):
        try:
            date_part = generated_at.split("T", 1)[0]
            run_date = datetime.fromisoformat(f"{date_part}T00:00:00+00:00")
        except ValueError:
            run_date = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)
    else:
        run_date = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)

    ends_at = run_date + timedelta(days=2)
    return {
        "id": f"refresh-delayed-{run_date.date().isoformat()}",
        "title": {
            "en": "Timetable refresh delayed",
            "ro": "Actualizarea orarului întârzie",
        },
        "message": {
            "en": (
                f"Latest refresh failed for {len(failures)} source(s). "
                "Showing the most recent successful timetable where available."
            ),
            "ro": (
                f"Ultima actualizare a eșuat pentru {len(failures)} surse. "
                "Afișăm cel mai recent orar actualizat cu succes, acolo unde este disponibil."
            ),
        },
        "severity": "warning",
        "symbolName": "exclamationmark.triangle.fill",
        "startsAt": run_date.isoformat().replace("+00:00", "Z"),
        "endsAt": ends_at.isoformat().replace("+00:00", "Z"),
    }


def _dedupe_items(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    deduped: list[dict[str, Any]] = []
    seen_ids: set[str] = set()
    for item in items:
        item_id = item.get("id")
        if not isinstance(item_id, str) or not item_id.strip():
            continue
        if item_id in seen_ids:
            continue
        seen_ids.add(item_id)
        deduped.append(item)
    return deduped


def _build_payloads(items: list[dict[str, Any]]) -> tuple[dict[str, Any], dict[str, Any]]:
    """Derive both feeds from one bilingual source without changing v1's shape."""
    legacy_items = []
    bilingual_items = []
    for item in _dedupe_items(items):
        legacy_language = item.get("legacyLanguage", "en")
        if legacy_language not in ("en", "ro"):
            raise ValueError(f"{item['id']}: legacyLanguage must be en or ro.")
        localized = {key: value for key, value in item.items() if key != "legacyLanguage"}
        legacy = dict(localized)
        for field in ("title", "message"):
            text = item.get(field)
            if not isinstance(text, dict) or set(text) != {"en", "ro"}:
                raise ValueError(f"{item['id']}: {field} must contain en and ro translations.")
            if any(not isinstance(value, str) or not value.strip() for value in text.values()):
                raise ValueError(f"{item['id']}: {field} translations must be non-empty strings.")
            localized[field] = dict(text)
            legacy[field] = text[legacy_language]
        legacy_items.append(legacy)
        bilingual_items.append(localized)
    generated_at = utc_now_iso()
    return (
        {"version": 1, "generatedAt": generated_at, "items": legacy_items},
        {"version": 2, "generatedAt": generated_at, "items": bilingual_items},
    )


def main() -> int:
    args = _parse_args()
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    manual_items = _load_manual_items(Path(args.announcements))
    status = _load_status(Path(args.status))
    auto_item = _auto_failure_announcement(status)

    all_items = list(manual_items)
    if auto_item:
        all_items.append(auto_item)
    all_items = _dedupe_items(all_items)

    legacy, bilingual = _build_payloads(all_items)
    write_json(out_dir / "announcements.json", legacy)
    write_json(out_dir / "announcements-v2.json", bilingual)
    print(f"Wrote {len(all_items)} announcements in v1 and v2.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
